version: '3'

services:
 nginx:
   image: nginx
   volumes:
     - .:/usr/share/
   ports:
     - "8080:80"
 nginx2:
   image: nginx
   volumes:
     - .:/usr/share/
   ports:
     - "9001:80"
 redis:
   image: redis
